name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  geocoder: ^0.2.1
  geolocator: ^6.0.0+4
  flutter_signin_button: ^1.0.0
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  uuid: ^2.2.2
  http: ^0.12.2
  countdown: ^0.1.0
  image_picker: ^0.6.7+7
  upi_pay: ^0.2.2
  shared_preferences: ^0.5.10
  toast: ^0.1.5
  firebase_storage: ^3.1.6




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/